version: "3.8"

services:
  go_cron_service:
    build: .
    container_name: go_cron_service
    restart: always
    volumes:
      - ./messages.db:/app/messages.db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    environment:
      - TZ=UTC
